api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php-composer"
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    purl = "pkg:generic/composer@2.2.9?checksum=48f9fdc9ad93904fee96550b45ae03a51f69718502ee855da894b4ad71d2dfe0&download_url=https://getcomposer.org/download/2.2.9/composer.phar"
    sha256 = "48f9fdc9ad93904fee96550b45ae03a51f69718502ee855da894b4ad71d2dfe0"
    source = "https://getcomposer.org/download/2.2.9/composer.phar"
    source_sha256 = "48f9fdc9ad93904fee96550b45ae03a51f69718502ee855da894b4ad71d2dfe0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/composer/composer_2.2.9_linux_noarch_any-stack_48f9fdc9.phar"
    version = "2.2.9"

  [[metadata.dependencies]]
    id = "composer"
    purl = "pkg:generic/composer@2.2.10?checksum=dc9dfdd2ffb1180d785b5a3d581c946ec6da135f55c9959f21b96fea7d7fb12d&download_url=https://getcomposer.org/download/2.2.10/composer.phar"
    sha256 = "dc9dfdd2ffb1180d785b5a3d581c946ec6da135f55c9959f21b96fea7d7fb12d"
    source = "https://getcomposer.org/download/2.2.10/composer.phar"
    source_sha256 = "dc9dfdd2ffb1180d785b5a3d581c946ec6da135f55c9959f21b96fea7d7fb12d"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/composer/composer_2.2.10_linux_noarch_any-stack_dc9dfdd2.phar"
    version = "2.2.10"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "composer"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
