api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php-composer"
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "3c8f521888ccb51becae522e263dbfd17169fbf3d4716685858b2c7e7684f4ae"
    source = "https://github.com/composer/composer/releases/download/2.1.4/composer.phar"
    source_sha256 = "3c8f521888ccb51becae522e263dbfd17169fbf3d4716685858b2c7e7684f4ae"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.1.4_linux_noarch_any-stack_3c8f5218.phar"
    version = "2.1.4"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "be95557cc36eeb82da0f4340a469bad56b57f742d2891892dcb2f8b0179790ec"
    source = "https://github.com/composer/composer/releases/download/2.1.5/composer.phar"
    source_sha256 = "be95557cc36eeb82da0f4340a469bad56b57f742d2891892dcb2f8b0179790ec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.1.5_linux_noarch_any-stack_be95557c.phar"
    version = "2.1.5"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
