api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php-composer"
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    purl = "pkg:generic/composer@2.3.4?checksum=1fc8fc5b43f081fe76fa85eb5a213412e55f54a60bae4880bc96521ae482d6c3&download_url=https://getcomposer.org/download/2.3.4/composer.phar"
    sha256 = "1fc8fc5b43f081fe76fa85eb5a213412e55f54a60bae4880bc96521ae482d6c3"
    source = "https://getcomposer.org/download/2.3.4/composer.phar"
    source_sha256 = "1fc8fc5b43f081fe76fa85eb5a213412e55f54a60bae4880bc96521ae482d6c3"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/composer/composer_2.3.4_linux_noarch_any-stack_1fc8fc5b.phar"
    version = "2.3.4"

  [[metadata.dependencies]]
    id = "composer"
    purl = "pkg:generic/composer@2.3.5?checksum=3b3b5a899c06a46aec280727bdf50aad14334f6bc40436ea76b07b650870d8f4&download_url=https://getcomposer.org/download/2.3.5/composer.phar"
    sha256 = "3b3b5a899c06a46aec280727bdf50aad14334f6bc40436ea76b07b650870d8f4"
    source = "https://getcomposer.org/download/2.3.5/composer.phar"
    source_sha256 = "3b3b5a899c06a46aec280727bdf50aad14334f6bc40436ea76b07b650870d8f4"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/composer/composer_2.3.5_linux_noarch_any-stack_3b3b5a89.phar"
    version = "2.3.5"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "composer"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
