api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php-composer"
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    purl = "pkg:generic/composer@2.2.6?checksum=1d58486b891e59e9e064c0d54bb38538f74d6014f75481542c69ad84d4e97704&download_url=https://getcomposer.org/download/2.2.6/composer.phar"
    sha256 = "1d58486b891e59e9e064c0d54bb38538f74d6014f75481542c69ad84d4e97704"
    source = "https://getcomposer.org/download/2.2.6/composer.phar"
    source_sha256 = "1d58486b891e59e9e064c0d54bb38538f74d6014f75481542c69ad84d4e97704"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/composer/composer_2.2.6_linux_noarch_any-stack_1d58486b.phar"
    version = "2.2.6"

  [[metadata.dependencies]]
    id = "composer"
    purl = "pkg:generic/composer@2.2.7?checksum=10040ded663541990eef8ce1f6fa44cb3b4a47e145efb8e9e59907a15068033d&download_url=https://getcomposer.org/download/2.2.7/composer.phar"
    sha256 = "10040ded663541990eef8ce1f6fa44cb3b4a47e145efb8e9e59907a15068033d"
    source = "https://getcomposer.org/download/2.2.7/composer.phar"
    source_sha256 = "10040ded663541990eef8ce1f6fa44cb3b4a47e145efb8e9e59907a15068033d"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/composer/composer_2.2.7_linux_noarch_any-stack_10040ded.phar"
    version = "2.2.7"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "composer"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
