api = "0.4"

[buildpack]
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/php-composer"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "be95557cc36eeb82da0f4340a469bad56b57f742d2891892dcb2f8b0179790ec"
    source = "https://github.com/composer/composer/releases/download/2.1.5/composer.phar"
    source_sha256 = "be95557cc36eeb82da0f4340a469bad56b57f742d2891892dcb2f8b0179790ec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.1.5_linux_noarch_any-stack_be95557c.phar"
    version = "2.1.5"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "72524ccebcb071968eb83284507225fdba59f223719b2b3f333d76c8a9ac6b72"
    source = "https://github.com/composer/composer/releases/download/2.1.6/composer.phar"
    source_sha256 = "72524ccebcb071968eb83284507225fdba59f223719b2b3f333d76c8a9ac6b72"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.1.6_linux_noarch_any-stack_72524cce.phar"
    version = "2.1.6"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
