api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php-composer"
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    purl = "pkg:generic/composer@2.1.9?checksum=4d00b70e146c17d663ad2f9a21ebb4c9d52b021b1ac15f648b4d371c04d648ba&download_url=https://getcomposer.org/download/2.1.9/composer.phar"
    sha256 = "4d00b70e146c17d663ad2f9a21ebb4c9d52b021b1ac15f648b4d371c04d648ba"
    source = "https://getcomposer.org/download/2.1.9/composer.phar"
    source_sha256 = "4d00b70e146c17d663ad2f9a21ebb4c9d52b021b1ac15f648b4d371c04d648ba"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/composer/composer_2.1.9_linux_noarch_any-stack_4d00b70e.phar"
    version = "2.1.9"

  [[metadata.dependencies]]
    id = "composer"
    purl = "pkg:generic/composer@2.1.10?checksum=cb8b04cc6a6fb167403f7495e8539650eb555657aa48873f115383bcd8f0b18d&download_url=https://getcomposer.org/download/2.1.10/composer.phar"
    sha256 = "cb8b04cc6a6fb167403f7495e8539650eb555657aa48873f115383bcd8f0b18d"
    source = "https://getcomposer.org/download/2.1.10/composer.phar"
    source_sha256 = "cb8b04cc6a6fb167403f7495e8539650eb555657aa48873f115383bcd8f0b18d"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/composer/composer_2.1.10_linux_noarch_any-stack_cb8b04cc.phar"
    version = "2.1.10"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "composer"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
